In [2]:
import numpy as np 

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a) 

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
b = np.array([[1,2,3], [3,4,5], [5,6,7]])
print(b) 

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [5]:
print(a.ndim)
print(b.ndim) 

1
2


In [7]:
arr = np.array(1)
print(arr)
print(arr.ndim) 

1
0


In [10]:
li = [1,2,3,4,5]
arr02 = np.array(li)
print(arr02)  

[1 2 3 4 5]


In [9]:
tu = (1,2,3,4,5)
arr03 = np.array(tu)
print(arr03) 

[1 2 3 4 5]
